<?php

/**
 * @file
 * Webform plugin for CAC contact element
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_cac_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.webform_cac':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform plugin for CAC customization.') . '</p>';
      return $output;

    default:
  }
}
